rvm: 2.2.2

language: objective-c

before_install: 
   - export LANG=en_US.UTF-8
   - gem uninstall cocoapods -a -x
   - gem install cocoapods --pre

before_script:
   - gem update cocoapods --pre --no-ri --no-rdoc
   - pod --version
   - sudo easy_install cpp-coveralls

script:
   - cd Project/PrYv-OSX-Example/
   - pod install
   - xcodebuild test -workspace PrYv-OSX-Example.xcworkspace -scheme PrYv-OSX-Example -verbose -configuration Coverage

after_success:
   - cd ../../
   - ./coveralls.rb --extension m --exclude-folder Project
